#!/usr/bin/env node

/**
 * TypeScript Type Collector
 *
 * This script finds all type and interface definitions in a TypeScript project,
 * collects them into a single file, and exports them all.
 */

const fs = require("fs")
const path = require("path")
const glob = require("glob")
const ts = require("typescript")

// Configuration
const SRC_DIR = path.resolve(process.cwd(), "src")
const OUTPUT_FILE = path.resolve(process.cwd(), "build/src/index.d.ts")
const GLOB_PATTERN = "**/*.ts"

const SUFFIX_TO_REMOVE = ["Response", "ObjectResponse"].sort(
  (a, b) => b.length - a.length
)

const SUFFIX_TO_NAMESPACE = ["Filter", "Parameters", "Request", "Config"]

// Create build directory and subdirectories if they don't exist
const outputDir = path.dirname(OUTPUT_FILE)
if (!fs.existsSync(outputDir)) {
  console.log(`Creating output directory: ${outputDir}`)
  fs.mkdirSync(outputDir, { recursive: true })
}

console.log("🔍 Scanning TypeScript files in:", SRC_DIR)

// Find all TypeScript files in the source directory
const tsFiles = glob.sync(GLOB_PATTERN, {
  cwd: SRC_DIR,
  absolute: true,
})

console.log(`Found ${tsFiles.length} TypeScript files.`)

// Collect type information
const namespaces = {
  default: [],
  ...SUFFIX_TO_NAMESPACE.reduce((acc, suffix) => {
    acc[suffix] = []
    return acc
  }, {}),
}
const baseStatements = []

// Parse TypeScript files and extract types
tsFiles.forEach(filePath => {
  const relativePath = path.relative(SRC_DIR, filePath)
  const sourceText = fs.readFileSync(filePath, "utf8")

  const sourceFile = ts.createSourceFile(
    filePath,
    sourceText,
    ts.ScriptTarget.Latest,
    true
  )

  // Check if file only imports from local files or has no imports
  let hasExternalImports = false

  ts.forEachChild(sourceFile, node => {
    if (ts.isImportDeclaration(node)) {
      const importPath = node.moduleSpecifier.text
      // If import doesn't start with './', consider it external
      if (!importPath.startsWith("./") && !importPath.startsWith("../")) {
        hasExternalImports = true
      }
    }
  })

  // Skip files with external imports
  if (hasExternalImports) {
    console.log(`Skipping file with external imports: ${relativePath}`)
    return
  }

  console.log(`Processing: ${relativePath}`)

  // Process the AST and extract type/interface definitions
  function visit(node) {
    // Helper function to check if a node has an export modifier
    const isExported = node => {
      return (
        node.modifiers &&
        node.modifiers.some(
          modifier => modifier.kind === ts.SyntaxKind.ExportKeyword
        )
      )
    }

    // Check for type, interface and enum declarations
    if (
      (ts.isTypeAliasDeclaration(node) ||
        ts.isInterfaceDeclaration(node) ||
        ts.isEnumDeclaration(node)) &&
      node.name
    ) {
      const nodeName = node.name.text
      const nodeType = {
        [ts.SyntaxKind.TypeAliasDeclaration]: "type",
        [ts.SyntaxKind.InterfaceDeclaration]: "interface",
        [ts.SyntaxKind.EnumDeclaration]: "enum",
      }[node.kind]

      // Get the actual start position of the declaration (excluding comments)
      let declarationText =
        (isExported(node) ? "" : "export ") +
        sourceText.substring(node.getStart(sourceFile), node.end).trim()

      // Add the declaration to the base namespace
      baseStatements.push(declarationText)

      if (nodeType !== "type") return

      let simpleName = nodeName

      const removeSuffix = suffixes => {
        simpleName = simpleName.replace(
          new RegExp(`^(\\S+?)(${suffixes.join("|")})$`),
          "$1"
        )
      }

      // Remove suffixes from the identifier
      removeSuffix(SUFFIX_TO_REMOVE)

      // Determine the namespace based on the suffix
      const namespace =
        SUFFIX_TO_NAMESPACE.find(suffix => simpleName.endsWith(suffix)) ??
        "default"

      // Remove the suffix from the identifier
      removeSuffix(SUFFIX_TO_NAMESPACE)

      // Check if the declaration already exists in the namespace

      // Add the declaration to the namespace
      namespaces[namespace].push(
        `export ${nodeType} ${simpleName} = Base.${nodeName}`
      )
    }

    // Visit children
    ts.forEachChild(node, visit)
  }

  visit(sourceFile)
})

// Generate the output file
let content = `/**
 * Auto-generated type definitions
 * Generated on: ${new Date().toISOString()}
 * 
 * This file contains all type, interface, and enum definitions from the project.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */


`

// Add default namespace declarations
content += namespaces.default.join("\n\n")

// Add other namespaces
for (const [namespace, declarations] of Object.entries(namespaces)) {
  if (namespace !== "default" && declarations.length > 0) {
    content += `\n\n// Namespace: ${namespace}\n`
    content += `export namespace ${namespace} {\n`
    content += declarations.join("\n\n")
    content += `\n}\n`
  }
}

// Add base statements
if (baseStatements.length > 0) {
  content += `\n\n// Base declarations\n`
  content += `export namespace Base {\n`
  content += baseStatements.join("\n\n")
  content += `\n}\n`
}

fs.writeFileSync(OUTPUT_FILE, content, "utf8")

const declarationCount = Object.values(namespaces).reduce(
  (sum, n) => sum + n.length,
  0
)

console.log(
  `✅ Successfully exported ${declarationCount} type definitions to: ${OUTPUT_FILE}`
)
console.log("Note: Files with external imports were skipped.")
